import React from 'react';
import { ContributingFactor } from '../types';

interface XAIExplanationProps {
  factors: ContributingFactor[];
  score: number;
}

export const XAIExplanation: React.FC<XAIExplanationProps> = ({ factors, score }) => {
  return (
    <div className="space-y-3">
      <div className="text-sm font-semibold text-white">
        Explainable AI: Why Is The Risk Level High?
      </div>
      <p className="text-xs text-slate-400">
        Transparent factor attribution generated by AlertNex prototype risk engine.
      </p>

      <div className="space-y-2.5 pt-2">
        {factors.map((f, idx) => {
          const impactBadgeClass =
            f.impact === 'HIGH'
              ? 'bg-red-500/20 text-red-400 border-red-500/40'
              : f.impact === 'MODERATE'
              ? 'bg-amber-500/20 text-amber-400 border-amber-500/40'
              : 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40';

          const pct = Math.min(Math.round((f.score / Math.max(score, 1)) * 100), 100);

          return (
            <div key={idx} className="bg-navy-900 border border-navy-600 rounded-lg p-3">
              <div className="flex items-center justify-between text-xs mb-1.5">
                <span className="font-semibold text-slate-200">{f.factor}</span>
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold border ${impactBadgeClass}`}>
                  {f.impact} IMPACT
                </span>
              </div>
              <div className="w-full h-1.5 bg-navy-950 rounded-full overflow-hidden mb-1">
                <div
                  className="h-full bg-gradient-to-r from-orange-500 to-red-500 rounded-full"
                  style={{ width: `${pct * 2}%` }}
                />
              </div>
              <div className="flex justify-between text-[11px] text-slate-400">
                <span>Contribution: {f.weight}</span>
                <span className="font-mono text-slate-300">+{f.score} pts</span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
